"""baseline

Revision ID: 727e99f305fa
Revises: 
Create Date: 2026-02-04 07:19:52.374196

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '727e99f305fa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('order_number', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('ship_to_address_id', sa.BigInteger(), nullable=False),
    sa.Column('delivered_address_id', sa.BigInteger(), nullable=True),
    sa.Column('tracking_number', sa.String(length=64), nullable=True),
    sa.Column('carrier', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_order_number'), ['order_number'], unique=True)

    with op.batch_alter_table('idempotency_key', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ux_idem'))

    op.drop_table('idempotency_key')
    with op.batch_alter_table('replacement_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ux_repl'))

    op.drop_table('replacement_link')
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_email'))
        batch_op.drop_index(batch_op.f('ux_customer_tenant_ref'))

    op.drop_table('customer')
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_address_customer'))

    op.drop_table('address')
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ux_user_tenant_username'))

    op.drop_table('app_user')
    with op.batch_alter_table('tracking_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_track_pkg_time'))

    op.drop_table('tracking_event')
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('tenant_key'))

    op.drop_table('tenant')
    with op.batch_alter_table('shipment_package', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pkg_ship'))
        batch_op.drop_index(batch_op.f('ux_pkg_track'))

    op.drop_table('shipment_package')
    with op.batch_alter_table('policy_rule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ux_policy'))

    op.drop_table('policy_rule')
    with op.batch_alter_table('shipment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ship_order'))

    op.drop_table('shipment')
    with op.batch_alter_table('sales_order_line', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_line_order'))
        batch_op.drop_index(batch_op.f('ux_line'))

    op.drop_table('sales_order_line')
    with op.batch_alter_table('agent_run', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ux_run_corr'))

    op.drop_table('agent_run')
    with op.batch_alter_table('support_ticket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_order'))
        batch_op.drop_index(batch_op.f('ux_ticket'))

    op.drop_table('support_ticket')
    with op.batch_alter_table('support_ticket_event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_evt'))

    op.drop_table('support_ticket_event')
    with op.batch_alter_table('tool_action_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_action_corr'))

    op.drop_table('tool_action_log')
    with op.batch_alter_table('sales_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_customer'))
        batch_op.drop_index(batch_op.f('ux_order_tenant_number'))

    op.drop_table('sales_order')
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ux_inv'))

    op.drop_table('inventory')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ux_product_tenant_sku'))

    op.drop_table('product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('product_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('sku', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], name=op.f('fk_product_tenant')),
    sa.PrimaryKeyConstraint('product_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ux_product_tenant_sku'), ['tenant_id', 'sku'], unique=True)

    op.create_table('inventory',
    sa.Column('inventory_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('product_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('location_code', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('on_hand_qty', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('reserved_qty', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], name=op.f('fk_inv_product')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], name=op.f('fk_inv_tenant')),
    sa.PrimaryKeyConstraint('inventory_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ux_inv'), ['tenant_id', 'product_id', 'location_code'], unique=True)

    op.create_table('sales_order',
    sa.Column('order_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('order_number', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('customer_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('bill_to_address_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('ship_to_address_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('order_status', mysql.ENUM('CREATED', 'PAID', 'FULFILLING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'CLOSED'), nullable=False),
    sa.Column('currency', mysql.CHAR(length=3), server_default=sa.text("'USD'"), nullable=False),
    sa.Column('order_total', mysql.DECIMAL(precision=12, scale=2), server_default=sa.text("'0.00'"), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['bill_to_address_id'], ['address.address_id'], name=op.f('fk_order_bill_to')),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], name=op.f('fk_order_customer')),
    sa.ForeignKeyConstraint(['ship_to_address_id'], ['address.address_id'], name=op.f('fk_order_ship_to')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], name=op.f('fk_order_tenant')),
    sa.PrimaryKeyConstraint('order_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('sales_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ux_order_tenant_number'), ['tenant_id', 'order_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_order_customer'), ['tenant_id', 'customer_id', 'created_at'], unique=False)

    op.create_table('tool_action_log',
    sa.Column('action_log_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('correlation_id', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('tool_name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('request_json', mysql.JSON(), nullable=False),
    sa.Column('response_json', mysql.JSON(), nullable=True),
    sa.Column('outcome', mysql.ENUM('OK', 'DENIED', 'ERROR'), nullable=False),
    sa.Column('error_message', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_by_user_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['app_user.user_id'], name=op.f('fk_tal_user')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], name=op.f('fk_tal_tenant')),
    sa.PrimaryKeyConstraint('action_log_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('tool_action_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_action_corr'), ['tenant_id', 'correlation_id', 'created_at'], unique=False)

    op.create_table('support_ticket_event',
    sa.Column('ticket_event_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ticket_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('event_type', mysql.ENUM('NOTE', 'STATUS_CHANGE', 'CUSTOMER_MESSAGE', 'SYSTEM_ACTION'), nullable=False),
    sa.Column('message', mysql.TEXT(), nullable=False),
    sa.Column('created_by_user_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['app_user.user_id'], name=op.f('fk_te_user')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], name=op.f('fk_te_tenant')),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_ticket.ticket_id'], name=op.f('fk_te_ticket')),
    sa.PrimaryKeyConstraint('ticket_event_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('support_ticket_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_evt'), ['tenant_id', 'ticket_id', 'created_at'], unique=False)

    op.create_table('support_ticket',
    sa.Column('ticket_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('ticket_number', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('customer_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('order_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('category', mysql.ENUM('DELIVERY_ISSUE', 'REPLACEMENT', 'REFUND', 'ADDRESS_CHANGE', 'OTHER'), nullable=False),
    sa.Column('priority', mysql.ENUM('LOW', 'NORMAL', 'HIGH', 'URGENT'), server_default=sa.text("'NORMAL'"), nullable=False),
    sa.Column('status', mysql.ENUM('OPEN', 'IN_PROGRESS', 'WAITING_CUSTOMER', 'RESOLVED', 'CLOSED'), server_default=sa.text("'OPEN'"), nullable=False),
    sa.Column('summary', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_by_user_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['app_user.user_id'], name=op.f('fk_ticket_user')),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], name=op.f('fk_ticket_customer')),
    sa.ForeignKeyConstraint(['order_id'], ['sales_order.order_id'], name=op.f('fk_ticket_order')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], name=op.f('fk_ticket_tenant')),
    sa.PrimaryKeyConstraint('ticket_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('support_ticket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ux_ticket'), ['tenant_id', 'ticket_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_ticket_order'), ['tenant_id', 'order_id'], unique=False)

    op.create_table('agent_run',
    sa.Column('agent_run_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('correlation_id', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('channel', mysql.ENUM('WEB_UI', 'API', 'BATCH'), server_default=sa.text("'WEB_UI'"), nullable=False),
    sa.Column('input_text', mysql.TEXT(), nullable=False),
    sa.Column('classification_json', mysql.JSON(), nullable=True),
    sa.Column('state_json', mysql.JSON(), nullable=True),
    sa.Column('final_response', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.ENUM('STARTED', 'COMPLETED', 'FAILED'), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], name=op.f('fk_run_tenant')),
    sa.PrimaryKeyConstraint('agent_run_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('agent_run', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ux_run_corr'), ['tenant_id', 'correlation_id'], unique=True)

    op.create_table('sales_order_line',
    sa.Column('order_line_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('order_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('line_no', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('sku', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('qty', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('unit_price', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('line_total', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('fulfillment_status', mysql.ENUM('OPEN', 'ALLOCATED', 'SHIPPED', 'DELIVERED', 'CANCELLED'), server_default=sa.text("'OPEN'"), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['sales_order.order_id'], name=op.f('fk_line_order')),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], name=op.f('fk_line_product')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], name=op.f('fk_line_tenant')),
    sa.PrimaryKeyConstraint('order_line_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('sales_order_line', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ux_line'), ['tenant_id', 'order_id', 'line_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_line_order'), ['tenant_id', 'order_id'], unique=False)

    op.create_table('shipment',
    sa.Column('shipment_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('order_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('carrier', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('service_level', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('ship_status', mysql.ENUM('CREATED', 'LABEL_CREATED', 'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'DELIVERED', 'EXCEPTION', 'RETURNED'), nullable=False),
    sa.Column('ship_from_location', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('shipped_at', mysql.DATETIME(), nullable=True),
    sa.Column('delivered_at', mysql.DATETIME(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['sales_order.order_id'], name=op.f('fk_ship_order')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], name=op.f('fk_ship_tenant')),
    sa.PrimaryKeyConstraint('shipment_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('shipment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ship_order'), ['tenant_id', 'order_id'], unique=False)

    op.create_table('policy_rule',
    sa.Column('policy_rule_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('rule_key', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('rule_json', mysql.JSON(), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], name=op.f('fk_policy_tenant')),
    sa.PrimaryKeyConstraint('policy_rule_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('policy_rule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ux_policy'), ['tenant_id', 'rule_key'], unique=True)

    op.create_table('shipment_package',
    sa.Column('package_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('shipment_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('tracking_number', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('weight_oz', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipment.shipment_id'], name=op.f('fk_pkg_ship')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], name=op.f('fk_pkg_tenant')),
    sa.PrimaryKeyConstraint('package_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('shipment_package', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ux_pkg_track'), ['tenant_id', 'tracking_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_pkg_ship'), ['tenant_id', 'shipment_id'], unique=False)

    op.create_table('tenant',
    sa.Column('tenant_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('tenant_key', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('status', mysql.ENUM('ACTIVE', 'SUSPENDED'), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('tenant_key'), ['tenant_key'], unique=True)

    op.create_table('tracking_event',
    sa.Column('event_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('package_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('event_time', mysql.DATETIME(), nullable=False),
    sa.Column('status_code', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('description', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('city', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('region', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('country', mysql.CHAR(length=2), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['shipment_package.package_id'], name=op.f('fk_track_pkg')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], name=op.f('fk_track_tenant')),
    sa.PrimaryKeyConstraint('event_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('tracking_event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_track_pkg_time'), ['tenant_id', 'package_id', 'event_time'], unique=False)

    op.create_table('app_user',
    sa.Column('user_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('display_name', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('role', mysql.ENUM('AGENT', 'SUPERVISOR', 'SYSTEM'), server_default=sa.text("'AGENT'"), nullable=False),
    sa.Column('status', mysql.ENUM('ACTIVE', 'DISABLED'), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], name=op.f('fk_user_tenant')),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('app_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ux_user_tenant_username'), ['tenant_id', 'username'], unique=True)

    op.create_table('address',
    sa.Column('address_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('customer_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('name_line', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('line1', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('line2', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('region', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('postal_code', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('country', mysql.CHAR(length=2), nullable=False),
    sa.Column('is_validated', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.customer_id'], name=op.f('fk_address_customer')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], name=op.f('fk_address_tenant')),
    sa.PrimaryKeyConstraint('address_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_address_customer'), ['tenant_id', 'customer_id'], unique=False)

    op.create_table('customer',
    sa.Column('customer_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('customer_ref', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('status', mysql.ENUM('ACTIVE', 'BLOCKED'), server_default=sa.text("'ACTIVE'"), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], name=op.f('fk_customer_tenant')),
    sa.PrimaryKeyConstraint('customer_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ux_customer_tenant_ref'), ['tenant_id', 'customer_ref'], unique=True)
        batch_op.create_index(batch_op.f('ix_customer_email'), ['email'], unique=False)

    op.create_table('replacement_link',
    sa.Column('replacement_link_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('original_order_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('replacement_order_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('reason_code', mysql.ENUM('WRONG_ADDRESS', 'LOST', 'DAMAGED', 'MISSING_ITEMS', 'OTHER'), nullable=False),
    sa.Column('created_by_user_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['app_user.user_id'], name=op.f('fk_repl_user')),
    sa.ForeignKeyConstraint(['original_order_id'], ['sales_order.order_id'], name=op.f('fk_repl_orig')),
    sa.ForeignKeyConstraint(['replacement_order_id'], ['sales_order.order_id'], name=op.f('fk_repl_new')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], name=op.f('fk_repl_tenant')),
    sa.PrimaryKeyConstraint('replacement_link_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('replacement_link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ux_repl'), ['tenant_id', 'original_order_id', 'replacement_order_id'], unique=True)

    op.create_table('idempotency_key',
    sa.Column('idempotency_id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('scope', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('idempotency_key', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('request_hash', mysql.CHAR(length=64), nullable=False),
    sa.Column('response_json', mysql.JSON(), nullable=True),
    sa.Column('status', mysql.ENUM('IN_PROGRESS', 'SUCCEEDED', 'FAILED'), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.tenant_id'], name=op.f('fk_idem_tenant')),
    sa.PrimaryKeyConstraint('idempotency_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('idempotency_key', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ux_idem'), ['tenant_id', 'scope', 'idempotency_key'], unique=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_order_number'))

    op.drop_table('orders')
    # ### end Alembic commands ###
